# Generated by Django 3.2.5 on 2021-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorialProjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('es_administrador', models.BooleanField()),
                ('es_corrector', models.BooleanField()),
                ('es_disenador', models.BooleanField()),
                ('es_editor', models.BooleanField()),
                ('es_maquetador', models.BooleanField()),
                ('es_traductor', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariobase',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_corrector',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_disenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_editor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_maquetador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='es_traductor',
            field=models.BooleanField(default=False),
        ),
    ]
