# Generated by Django 3.2.5 on 2021-12-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorialProjects', '0004_alter_tarea_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='importe',
            field=models.FloatField(),
        ),
    ]
