# Generated by Django 3.2.5 on 2021-12-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EditorialProjects', '0006_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='importe',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorialProjects.serie')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EditorialProjects.proyecto'),
        ),
    ]
