# Generated by Django 3.2.5 on 2021-12-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorialProjects', '0007_auto_20211208_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='no_entrega',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
