# Generated by Django 3.2.5 on 2021-12-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EditorialProjects', '0008_proyecto_no_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
